[package]
name = "wat"
version = "0.1.0"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2"
rayon = "1"

[build-dependencies]
rustc_tools_util = "0.2.0"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
